[package]
name = "scharnhorst_inspector"
version.workspace = true
edition = "2021"
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
scharnhorst_core = { workspace = true }
scharnhorst_query = { workspace = true }
scharnhorst_journal = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }

[dev-dependencies]
scharnhorst_schema = { workspace = true }
scharnhorst_arrow_store = { workspace = true }
scharnhorst_core = { workspace = true }
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
serde_json = { workspace = true }